abstracts = [
  '''Importance:  Reported cases of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) infection likely underestimate the prevalence of infection in affected communities. Large-scale seroprevalence studies provide better estimates of the proportion of the population previously infected.
Objective:  To estimate prevalence of SARS-CoV-2 antibodies in convenience samples from several geographic sites in the US.
Design, Setting, and Participants:  This cross-sectional study performed serologic testing on a convenience sample of residual sera obtained from persons of all ages. The serum was collected from March 23 through May 12, 2020, for routine clinical testing by 2 commercial laboratory companies. Sites of collection were San Francisco Bay area, California; Connecticut; south Florida; Louisiana; Minneapolis-St Paul-St Cloud metro area, Minnesota; Missouri; New York City metro area, New York; Philadelphia metro area, Pennsylvania; Utah; and western Washington State.
Exposures:  Infection with SARS-CoV-2.
Main Outcomes and Measures:  The presence of antibodies to SARS-CoV-2 spike protein was estimated using an enzyme-linked immunosorbent assay, and estimates were standardized to the site populations by age and sex. Estimates were adjusted for test performance characteristics (96.0% sensitivity and 99.3% specificity). The number of infections in each site was estimated by extrapolating seroprevalence to site populations; estimated infections were compared with the number of reported coronavirus disease 2019 (COVID-19) cases as of last specimen collection date.
Results:  Serum samples were tested from 16 025 persons, 8853 (55.2%) of whom were women; 1205 (7.5%) were 18 years or younger and 5845 (36.2%) were 65 years or older. Most specimens from each site had no evidence of antibodies to SARS-CoV-2. Adjusted estimates of the proportion of persons seroreactive to the SARS-CoV-2 spike protein antibodies ranged from 1.0% in the San Francisco Bay area (collected April 23-27) to 6.9% of persons in New York City (collected March 23-April 1). The estimated number of infections ranged from 6 to 24 times the number of reported cases; for 7 sites (Connecticut, Florida, Louisiana, Missouri, New York City metro area, Utah, and western Washington State), an estimated greater than 10 times more SARS-CoV-2 infections occurred than the number of reported cases.''',
  '''Background The province of British Columbia (BC) has been recognized for successful SARS-CoV-2 control, with surveillance data showing amongst the lowest case and death rates in Canada. We estimate sero-prevalence for two periods flanking the start (March) and end (May) of first-wave mitigation measures in BC.
Methods Serial cross-sectional sampling was conducted using anonymized residual sera obtained from an outpatient laboratory network, including children and adults in the Greater Vancouver Area (population ∼3 million) where community attack rates were expected to be highest. Screening used two chemiluminescent immuno-assays for spike (S1) and nucleocapsid antibodies. Samples sero-positive on either screening assay were assessed by a third assay targeting the S1 receptor binding domain plus a neutralization assay. Age-standardized sero-prevalence estimates were based on dual-assay positivity. The May sero-prevalence estimate was extrapolated to the source population to assess surveillance under-ascertainment, quantified as the ratio of estimated infections versus reported cases.
Results Serum collection dates spanned March 5-13 and May 15-27, 2020. In March, two of 869 specimens were dual-assay positive, with age-standardized sero-prevalence of 0.28% (95%CI=0.03-0.95). Neither specimen had detectable neutralizing antibodies. In May, four of 885 specimens were dual-assay positive, with age-standardized sero-prevalence of 0.55% (95%CI=0.15-1.37%). All four specimens had detectable neutralizing antibodies. We estimate ∼8 times more infections than reported cases.''',
  '''Background: Knowledge about the COVID-19 outbreak is still sparse especially in a cross-national setting. COVID-19 is caused by a SARS-CoV-2 infection. The aim of the study is to contribute to the surveillance of the pandemic by bringing new knowledge about SARS-CoV-2 seropositivity among healthcare workers and evaluating whether certain job functions is associated with a higher risk of being infected, and to clarify if such association is mediated by the number of individuals that the employees meet during a workday. Finally, we will investigate regional and national differences in seroprevalence. Methods: A bi-national prospective observational cohort study including 3,272 adults employed at Falck in Sweden and Denmark. Participants were tested for SARS-CoV-2 antibodies every second week for a period of 8 weeks from June 22, 2020 until August 10, 2020. Descriptive statistics as well as multivariable logistic regression analyses were applied. Results: Of the 3,272 Falck employees participating in this study, 159 (4.9%) tested positive for SARS-CoV-2 antibodies. The seroprevalence was lower among Danish Falck employees than among those from Sweden (2.8% in Denmark and 8.3% in Sweden). We also found that number of customer or patient contacts during a workday was the most prominent predictor for seropositivity, and that ambulance staff was the most vulnerable staff group. Conclusions: Our study presents geographical variations in seroprevalence within the Falck organization and shows evidence that social interaction is one of the biggest risk factors for getting infected with SARS-CoV-2.'''
]

def get_abstract(i):
  return abstracts[i]